// resources/js/components/Section.vue
<template>
    <div class="bg-card text-card-foreground rounded-xl border shadow-sm">
        <!-- Section Header -->
        <header v-if="heading" :class="['px-6 py-4 transition-all duration-200', isCollapsed ? '' : 'border-b']">
            <div
                :class="[
                    'flex items-center gap-3',
                    collapsible ? 'cursor-pointer select-none' : ''
                ]"
                @click="collapsible && toggleCollapse()"
                :role="collapsible ? 'button' : undefined"
                :tabindex="collapsible ? 0 : undefined"
                :aria-expanded="collapsible ? String(!isCollapsed) : undefined"
                @keydown.enter.prevent="collapsible && toggleCollapse()"
                @keydown.space.prevent="collapsible && toggleCollapse()"
            >
                <div
                    v-if="icon && getIconComponent(icon)"
                    class="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary flex-shrink-0"
                >
                    <component
                        :is="getIconComponent(icon)"
                        class="h-5 w-5"
                    />
                </div>
                <div class="flex-1 min-w-0">
                    <h3 class="leading-none font-semibold">
                        {{ heading }}
                    </h3>
                    <p v-if="description" class="mt-1 text-sm text-muted-foreground">
                        {{ description }}
                    </p>
                </div>
                <ChevronDown
                    v-if="collapsible"
                    :class="[
                        'h-4 w-4 text-muted-foreground transition-transform duration-200 ease-out flex-shrink-0',
                        isCollapsed ? '-rotate-90 rtl:rotate-90' : ''
                    ]"
                />
            </div>
        </header>

        <!-- Section Content with smooth collapse -->
        <div
            class="grid transition-all duration-200 ease-out"
            :style="{ gridTemplateRows: isCollapsed ? '0fr' : '1fr' }"
        >
            <div class="overflow-hidden">
                <div class="p-6 space-y-6">
                    <Schema
                        v-if="schema && schema.length > 0"
                        :schema="schema"
                        :model-value="modelValue"
                        :form-controller="formController"
                        :form-method="formMethod"
                        @update:model-value="$emit('update:modelValue', $event)"
                    />
                </div>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref, inject } from 'vue'
import { ChevronDown } from 'lucide-vue-next'
import * as LucideIcons from 'lucide-vue-next'
import Schema from './Schema.vue'

// Inject parent context for reactive fields
const formController = inject<string | undefined>('formController', undefined)
const formMethod = inject<string | undefined>('formMethod', 'getSchema')

const props = defineProps<{
    heading?: string
    description?: string
    icon?: string
    collapsible?: boolean
    collapsed?: boolean
    schema?: Array<any>
    modelValue?: Record<string, any>
}>()

const emit = defineEmits<{
    'update:modelValue': [value: Record<string, any>]
}>()

const isCollapsed = ref(props.collapsed || false)

const toggleCollapse = () => {
    if (props.collapsible) {
        isCollapsed.value = !isCollapsed.value
    }
}

// Convert kebab-case or snake_case icon names to PascalCase for lucide-vue-next
const getIconComponent = (iconName: string) => {
    if (!iconName) return null

    // Convert formats like 'user', 'id-card', 'map-pin' to PascalCase
    const pascalCase = iconName
        .split(/[-_]/)
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join('')

    return (LucideIcons as any)[pascalCase] || null
}
</script>

// resources/react/components/Section.tsx
import { cn } from '@/lib/utils';
import { useSchemaContext } from '@laravilt/support/composables/contexts';
import { resolveIcon } from '@laravilt/support/lib/icons';
import { ChevronDown } from 'lucide-react';
import { useState } from 'react';
import Schema from './Schema';

export interface SectionProps {
    heading?: string;
    description?: string;
    icon?: string;
    collapsible?: boolean;
    collapsed?: boolean;
    schema?: Array<any>;
    modelValue?: Record<string, any>;
    onUpdateModelValue?: (value: Record<string, any>) => void;
}

export default function Section({
    heading,
    description,
    icon,
    collapsible,
    collapsed,
    schema,
    modelValue,
    onUpdateModelValue,
}: SectionProps) {
    // Inject parent context for reactive fields
    const { formController, formMethod = 'getSchema' } = useSchemaContext();

    const [isCollapsed, setIsCollapsed] = useState<boolean>(collapsed || false);

    const toggleCollapse = () => {
        if (collapsible) {
            setIsCollapsed((value) => !value);
        }
    };

    const Icon = icon ? resolveIcon(icon) : null;

    return (
        <div className="bg-card text-card-foreground rounded-xl border shadow-sm">
            {/* Section Header */}
            {heading ? (
                <header className={cn('px-6 py-4 transition-all duration-200', isCollapsed ? '' : 'border-b')}>
                    <div
                        className={cn('flex items-center gap-3', collapsible ? 'cursor-pointer select-none' : '')}
                        onClick={() => collapsible && toggleCollapse()}
                        // Keyboard access for the collapsible header (a native button cannot contain the h3/p)
                        role={collapsible ? 'button' : undefined}
                        tabIndex={collapsible ? 0 : undefined}
                        aria-expanded={collapsible ? !isCollapsed : undefined}
                        onKeyDown={
                            collapsible
                                ? (event) => {
                                      if (event.key === 'Enter' || event.key === ' ') {
                                          event.preventDefault();
                                          toggleCollapse();
                                      }
                                  }
                                : undefined
                        }
                    >
                        {Icon ? (
                            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary flex-shrink-0">
                                <Icon className="h-5 w-5" />
                            </div>
                        ) : null}
                        <div className="flex-1 min-w-0">
                            <h3 className="leading-none font-semibold">{heading}</h3>
                            {description ? <p className="mt-1 text-sm text-muted-foreground">{description}</p> : null}
                        </div>
                        {collapsible ? (
                            <ChevronDown
                                className={cn(
                                    'h-4 w-4 text-muted-foreground transition-transform duration-200 ease-out flex-shrink-0',
                                    isCollapsed ? '-rotate-90 rtl:rotate-90' : '',
                                )}
                            />
                        ) : null}
                    </div>
                </header>
            ) : null}

            {/* Section Content with smooth collapse */}
            <div className="grid transition-all duration-200 ease-out" style={{ gridTemplateRows: isCollapsed ? '0fr' : '1fr' }}>
                <div className="overflow-hidden">
                    <div className="p-6 space-y-6">
                        {schema && schema.length > 0 ? (
                            <Schema
                                schema={schema}
                                modelValue={modelValue}
                                formController={formController}
                                formMethod={formMethod}
                                onUpdateModelValue={(value) => onUpdateModelValue?.(value)}
                            />
                        ) : null}
                    </div>
                </div>
            </div>
        </div>
    );
}
