// resources/js/components/Split.vue
<template>
    <div :class="gridClasses" :dir="rtl ? 'rtl' : 'ltr'">
        <div :class="startClasses">
            <Schema
                v-if="startSchema.length > 0"
                :schema="startSchema"
                :model-value="modelValue"
                :form-controller="formController"
                :form-method="formMethod"
                @update:model-value="$emit('update:modelValue', $event)"
            />
        </div>
        <div :class="endClasses">
            <Schema
                v-if="endSchema.length > 0"
                :schema="endSchema"
                :model-value="modelValue"
                :form-controller="formController"
                :form-method="formMethod"
                @update:model-value="$emit('update:modelValue', $event)"
            />
        </div>
    </div>
</template>

<script setup lang="ts">
import { computed, inject } from 'vue'
import Schema from './Schema.vue'
import { getSplitGridClasses, getSplitSpanClasses } from '../lib/layout'

// Inject parent context for reactive fields
const formController = inject<string | undefined>('formController', undefined)
const formMethod = inject<string | undefined>('formMethod', 'getSchema')

const props = withDefaults(defineProps<{
    startSchema?: Array<any>
    endSchema?: Array<any>
    startColumnSpan?: string | number
    endColumnSpan?: string | number
    fromBreakpoint?: string
    rtl?: boolean
    theme?: string
    modelValue?: Record<string, any>
}>(), {
    startSchema: () => [],
    endSchema: () => [],
    // Numeric so getSplitSpanClasses applies it from `fromBreakpoint` (a fixed `md:` class would not)
    startColumnSpan: 6,
    endColumnSpan: 6,
    fromBreakpoint: 'md',
    rtl: false,
    theme: 'light',
})

defineEmits<{
    'update:modelValue': [value: Record<string, any>]
}>()

const gridClasses = computed(() => getSplitGridClasses(props.fromBreakpoint))
const startClasses = computed(() => getSplitSpanClasses(props.startColumnSpan, props.fromBreakpoint))
const endClasses = computed(() => getSplitSpanClasses(props.endColumnSpan, props.fromBreakpoint))
</script>

// resources/react/components/Split.tsx
import { useSchemaContext } from '@laravilt/support/composables/contexts';
import { getSplitGridClasses, getSplitSpanClasses } from '../lib/layout';
import Schema from './Schema';

export interface SplitProps {
    startSchema?: Array<any>;
    endSchema?: Array<any>;
    startColumnSpan?: string | number;
    endColumnSpan?: string | number;
    fromBreakpoint?: string;
    rtl?: boolean;
    theme?: string;
    modelValue?: Record<string, any>;
    onUpdateModelValue?: (value: Record<string, any>) => void;
}

const EMPTY: any[] = [];

export default function Split({
    startSchema = EMPTY,
    endSchema = EMPTY,
    // Numeric so getSplitSpanClasses applies it from `fromBreakpoint` (a fixed `md:` class would not)
    startColumnSpan = 6,
    endColumnSpan = 6,
    fromBreakpoint = 'md',
    rtl = false,
    modelValue,
    onUpdateModelValue,
}: SplitProps) {
    // Inject parent context for reactive fields
    const { formController, formMethod = 'getSchema' } = useSchemaContext();

    const renderSide = (sideSchema: any[]) =>
        sideSchema.length > 0 ? (
            <Schema
                schema={sideSchema}
                modelValue={modelValue}
                formController={formController}
                formMethod={formMethod}
                onUpdateModelValue={(value) => onUpdateModelValue?.(value)}
            />
        ) : null;

    return (
        <div className={getSplitGridClasses(fromBreakpoint)} dir={rtl ? 'rtl' : 'ltr'}>
            <div className={getSplitSpanClasses(startColumnSpan, fromBreakpoint)}>{renderSide(startSchema)}</div>
            <div className={getSplitSpanClasses(endColumnSpan, fromBreakpoint)}>{renderSide(endSchema)}</div>
        </div>
    );
}
