// resources/js/components/Wizard.vue
<template>
    <div class="wizard" :dir="rtl ? 'rtl' : 'ltr'">
        <!-- Step Indicators -->
        <div class="wizard-steps">
            <div
                v-for="(step, index) in steps"
                :key="index"
                :class="[
                    'wizard-step',
                    {
                        'active': currentStepIndex === index,
                        'completed': currentStepIndex > index
                    }
                ]"
            >
                <div class="wizard-step-indicator">
                    <span v-if="step.icon" v-html="step.icon"></span>
                    <span v-else v-text="index + 1"></span>
                </div>
                <div class="wizard-step-label">
                    <div class="wizard-step-title" v-text="step.label"></div>
                    <div v-if="step.description" class="wizard-step-description" v-text="step.description"></div>
                </div>
            </div>
        </div>

        <!-- Step Content -->
        <div class="wizard-content">
            <div
                v-for="(step, index) in steps"
                :key="index"
                v-show="currentStepIndex === index"
                class="wizard-step-content"
            >
                <component
                    v-for="(child, childIndex) in step.schema"
                    :key="childIndex"
                    :is="child.component || 'div'"
                    v-bind="child"
                />
            </div>
        </div>

        <!-- Navigation -->
        <div class="wizard-navigation">
            <button
                v-if="currentStepIndex > 0"
                type="button"
                @click="previousStep"
                class="wizard-button wizard-button-previous"
                v-text="translatedPreviousButtonLabel"
            ></button>

            <button
                v-if="skippable && !isLastStep"
                type="button"
                @click="skipStep"
                class="wizard-button wizard-button-skip"
                v-text="translatedSkipButtonLabel"
            ></button>

            <button
                v-if="!isLastStep"
                type="button"
                @click="nextStep"
                class="wizard-button wizard-button-next"
                v-text="translatedNextButtonLabel"
            ></button>

            <button
                v-if="isLastStep"
                type="submit"
                class="wizard-button wizard-button-submit"
                v-text="translatedSubmitButtonLabel"
            ></button>
        </div>
    </div>
</template>

<script setup>
import { ref, computed } from 'vue';
import { useLocalization } from '@laravilt/support/composables';

// Initialize localization
const { trans } = useLocalization();

const props = defineProps({
    steps: {
        type: Array,
        default: () => []
    },
    currentStep: {
        type: Number,
        default: 0
    },
    skippable: {
        type: Boolean,
        default: false
    },
    submitButtonLabel: {
        type: String,
        default: 'Submit'
    },
    nextButtonLabel: {
        type: String,
        default: 'Next'
    },
    previousButtonLabel: {
        type: String,
        default: 'Previous'
    },
    skipButtonLabel: {
        type: String,
        default: 'Skip'
    },
    rtl: {
        type: Boolean,
        default: false
    },
    theme: {
        type: String,
        default: 'light'
    }
});

const currentStepIndex = ref(props.currentStep);

// Computed translated labels
const translatedSubmitButtonLabel = computed(() => props.submitButtonLabel !== 'Submit' ? props.submitButtonLabel : trans('wizard.submit_button_label'));
const translatedNextButtonLabel = computed(() => props.nextButtonLabel !== 'Next' ? props.nextButtonLabel : trans('wizard.next_button_label'));
const translatedPreviousButtonLabel = computed(() => props.previousButtonLabel !== 'Previous' ? props.previousButtonLabel : trans('wizard.previous_button_label'));
const translatedSkipButtonLabel = computed(() => props.skipButtonLabel !== 'Skip' ? props.skipButtonLabel : trans('wizard.skip_button_label'));

const isLastStep = computed(() => {
    return currentStepIndex.value === props.steps.length - 1;
});

const nextStep = () => {
    if (currentStepIndex.value < props.steps.length - 1) {
        currentStepIndex.value++;
    }
};

const previousStep = () => {
    if (currentStepIndex.value > 0) {
        currentStepIndex.value--;
    }
};

const skipStep = () => {
    if (props.skippable && currentStepIndex.value < props.steps.length - 1) {
        currentStepIndex.value++;
    }
};
</script>

// resources/react/components/Wizard.tsx
import { cn } from '@/lib/utils';
import { resolveComponent } from '@laravilt/support/composables/registry';
import { useLocalization } from '@laravilt/support/composables/useLocalization';
import { useState } from 'react';

export interface WizardProps {
    steps?: Array<any>;
    currentStep?: number;
    skippable?: boolean;
    submitButtonLabel?: string;
    nextButtonLabel?: string;
    previousButtonLabel?: string;
    skipButtonLabel?: string;
    rtl?: boolean;
    theme?: string;
}

// Vue `<component :is="child.component || 'div'" v-bind="child" />`: resolve the registered component, else a plain div
const renderChild = (child: any, childIndex: number) => {
    const Component = resolveComponent(child.component);

    if (!Component) {
        return <div key={childIndex} />;
    }

    return <Component key={childIndex} {...child} />;
};

export default function Wizard({
    steps = [],
    currentStep = 0,
    skippable = false,
    submitButtonLabel = 'Submit',
    nextButtonLabel = 'Next',
    previousButtonLabel = 'Previous',
    skipButtonLabel = 'Skip',
    rtl = false,
}: WizardProps) {
    // Initialize localization
    const { trans } = useLocalization();

    const [currentStepIndex, setCurrentStepIndex] = useState<number>(currentStep);

    // Translated labels
    const translatedSubmitButtonLabel = submitButtonLabel !== 'Submit' ? submitButtonLabel : trans('wizard.submit_button_label');
    const translatedNextButtonLabel = nextButtonLabel !== 'Next' ? nextButtonLabel : trans('wizard.next_button_label');
    const translatedPreviousButtonLabel =
        previousButtonLabel !== 'Previous' ? previousButtonLabel : trans('wizard.previous_button_label');
    const translatedSkipButtonLabel = skipButtonLabel !== 'Skip' ? skipButtonLabel : trans('wizard.skip_button_label');

    const isLastStep = currentStepIndex === steps.length - 1;

    const nextStep = () => {
        setCurrentStepIndex((index) => (index < steps.length - 1 ? index + 1 : index));
    };

    const previousStep = () => {
        setCurrentStepIndex((index) => (index > 0 ? index - 1 : index));
    };

    const skipStep = () => {
        setCurrentStepIndex((index) => (skippable && index < steps.length - 1 ? index + 1 : index));
    };

    return (
        <div className="wizard" dir={rtl ? 'rtl' : 'ltr'}>
            {/* Step Indicators */}
            <div className="wizard-steps">
                {steps.map((step: any, index: number) => (
                    <div
                        key={index}
                        className={cn('wizard-step', {
                            active: currentStepIndex === index,
                            completed: currentStepIndex > index,
                        })}
                    >
                        <div className="wizard-step-indicator">
                            {step.icon ? <span dangerouslySetInnerHTML={{ __html: step.icon }}></span> : <span>{index + 1}</span>}
                        </div>
                        <div className="wizard-step-label">
                            <div className="wizard-step-title">{step.label}</div>
                            {step.description ? <div className="wizard-step-description">{step.description}</div> : null}
                        </div>
                    </div>
                ))}
            </div>

            {/* Step Content */}
            <div className="wizard-content">
                {steps.map((step: any, index: number) => (
                    <div
                        key={index}
                        className="wizard-step-content"
                        style={currentStepIndex === index ? undefined : { display: 'none' }}
                    >
                        {(step.schema || []).map(renderChild)}
                    </div>
                ))}
            </div>

            {/* Navigation */}
            <div className="wizard-navigation">
                {currentStepIndex > 0 ? (
                    <button type="button" onClick={previousStep} className="wizard-button wizard-button-previous">
                        {translatedPreviousButtonLabel}
                    </button>
                ) : null}

                {skippable && !isLastStep ? (
                    <button type="button" onClick={skipStep} className="wizard-button wizard-button-skip">
                        {translatedSkipButtonLabel}
                    </button>
                ) : null}

                {!isLastStep ? (
                    <button type="button" onClick={nextStep} className="wizard-button wizard-button-next">
                        {translatedNextButtonLabel}
                    </button>
                ) : null}

                {isLastStep ? (
                    <button type="submit" className="wizard-button wizard-button-submit">
                        {translatedSubmitButtonLabel}
                    </button>
                ) : null}
            </div>
        </div>
    );
}
