// resources/react/components/Grid.tsx
import { useSchemaContext } from '@laravilt/support/composables/contexts';
import { getColumnSpanClasses, getGridClasses } from '../lib/layout';
import Schema from './Schema';

export interface GridProps {
    columns: number | Record<string, number>;
    schema: Array<any>;
    modelValue?: Record<string, any>;
    onUpdateModelValue?: (value: Record<string, any>) => void;
}

export default function Grid({ columns, schema, modelValue, onUpdateModelValue }: GridProps) {
    // Inject parent context for reactive fields
    const { formController, formMethod = 'getSchema' } = useSchemaContext();

    if (!(schema && schema.length > 0)) {
        return null;
    }

    // Static class maps (see lib/layout.ts) so Tailwind keeps every class
    return (
        <div className={getGridClasses(columns)}>
            {schema.map((child: any, index: number) => (
                <div key={child.name || child.id || index} className={getColumnSpanClasses(child.columnSpan)}>
                    <Schema
                        schema={[child]}
                        modelValue={modelValue}
                        formController={formController}
                        formMethod={formMethod}
                        onUpdateModelValue={(value) => onUpdateModelValue?.(value)}
                    />
                </div>
            ))}
        </div>
    );
}

// resources/js/components/Grid.vue
<template>
    <div v-if="schema && schema.length > 0" :class="gridClasses">
        <div
            v-for="(child, index) in schema"
            :key="child.name || child.id || index"
            :class="getColumnSpanClasses(child.columnSpan)"
        >
            <Schema
                :schema="[child]"
                :model-value="modelValue"
                :form-controller="formController"
                :form-method="formMethod"
                @update:model-value="$emit('update:modelValue', $event)"
            />
        </div>
    </div>
</template>

<script setup lang="ts">
import { computed, inject } from 'vue'
import Schema from './Schema.vue'
import { getColumnSpanClasses, getGridClasses } from '../lib/layout'

// Inject parent context for reactive fields
const formController = inject<string | undefined>('formController', undefined)
const formMethod = inject<string | undefined>('formMethod', 'getSchema')

const props = defineProps<{
    columns: number | Record<string, number>
    schema: Array<any>
    modelValue?: Record<string, any>
}>()

defineEmits<{
    'update:modelValue': [value: Record<string, any>]
}>()

// Static class maps (see lib/layout.ts) so Tailwind keeps every class
const gridClasses = computed(() => getGridClasses(props.columns))
</script>
